[package]
name = "i_am_alive_today"
version = "0.1.0"
description = "Do you know? I am alive today."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.5"
des = "0.7.0"
rsa = "0.5.0"
base64 = "0.13.0"

serde = "1.0"
serde_yaml = "0.8"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
