[package]
name = "i_am_alive_today"
version = "0.1.0"
description = "Do you know? I am alive today."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
