[package]
name = "i_am_alive_today"
version = "0.1.0"
description = "Do you know? I am alive today."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
openssl = "0.10.38"
curl = "0.4.39"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde_urlencoded = "0.7"
tempfile = "3.2.0"
urlencoding = "2.1.0"
uuid = { version = "0.8", features = ["v4"] }
