on:
  release:
    types: [published]
name: Upload Release Artifact
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Use Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Install vcpkg
        if: ${{ matrix.os == 'windows-latest' }}
        uses: lukka/run-vcpkg@v10
      - name: Install OpenSSL
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd vcpkg
          vcpkg install openssl:x64-windows-static-md
          vcpkg integrate install
          cd .. 
      - name: Build
        uses: actions-rs/cargo@v1
        env: 
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        with: 
          command: build
          args: --release --locked --features "telemetry"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/i_am_alive_today${{ matrix.ext }}
          asset_name: alivetoday-${{matrix.target}}${{matrix.ext}}
          asset_content_type: application/octet-stream

        
